version: '3'
services:
  client:
    container_name: next
    restart: always
    build:
      context: ./src/client
    volumes:
      - './src/client:/client'
    ports:
      - '3000:3000'
    links:
      - app
    depends_on:
      - app
  app:
    container_name: docker-node-mongo
    restart: always
    build:
      context: ./src/server
    volumes:
      - './src/server:/server'
    ports:
      - '8000:8000'
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://mongo:27017/naruto
      PORT: 8000
  mongo:
    container_name: mongo
    volumes:
      - './mongo:/data/db'
    image: mongo:4.2.8
    ports:
      - '27017:27017'
